import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

/*--- Install Roboto font from next/font/local ---*/
const myFont = localFont({
  // Import multiple font files.
  src: [
    { path: "./Roboto-Thin.ttf", weight: "100" },
    {
      path: "./Roboto-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-roboto", // Define a CSS variable for the font using with tailwindcss.
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable}`}>{children}</body>
    </html>
  );
}
